<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LoginCSV</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>087e131f-954e-4a8b-bcde-c350de96080f</testSuiteGuid>
   <testCaseLink>
      <guid>b367a6db-8816-4fb8-a81b-be7bac0a1e41</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/INICIAR SESION/LoginCSV</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0028555c-58d9-44f9-80b9-cd91416242b0</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DataLoginCSV/Login</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>0028555c-58d9-44f9-80b9-cd91416242b0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>eb25f973-8e21-4a2f-9030-fdddcadce145</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0028555c-58d9-44f9-80b9-cd91416242b0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>97017d39-9abe-487f-b4ff-a5b08c46874f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
